name: lightworks
base: core18
version: '14.5.0.0'
summary: Hollywood-strength editing for everyone
description: |
  Lightworks is the fastest, most accessible and focused NLE in the industry,
  because it is based on the  simple idea that the editor, not the computer
  industry, knows what’s best. The latest release of Lightworks is based on
  the cumulative knowledge from twenty years of top-flight editing.

grade: stable
confinement: strict

architectures:
  - build-on: amd64

layout:
  /usr/share/lightworks:
    bind: $SNAP/usr/share/lightworks
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib

parts:
  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins

  lightworks:
    after: [alsa-mixin]
    plugin: dump
    source: https://cdn.lwks.com/lightworks-14.5.0-amd64.deb
    override-build: |
      snapcraftctl build
      # Patch the path for $allusers
      sed -i 's|allusers=|allusers=$SNAP|' ${SNAPCRAFT_PART_INSTALL}/usr/bin/lightworks
      # Patch the path to ntcardvt
      sed -i 's|GDK_BACKEND=x11 |GDK_BACKEND=x11 $SNAP|' ${SNAPCRAFT_PART_INSTALL}/usr/bin/lightworks
    stage-packages:
     - libc++1
     - libglu1-mesa
     - libportaudiocpp0
     - libssl1.0.0
     - nvidia-cg-toolkit
     - ocl-icd-libopencl1
  cleanup:
    after: [lightworks]
    plugin: nil
    build-snaps: [ gnome-3-28-1804 ]
    override-prime: |
        set -eux
        cd /snap/gnome-3-28-1804/current
        find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/{} \;

apps:
  lightworks:
    command: usr/lib/lightworks/ntcardvt
    command-chain: [snap/command-chain/alsa-launch]
    desktop: usr/share/applications/lightworks.desktop
    extensions: [gnome-3-28]
    plugs:
      - audio-playback
      - audio-record
      - hardware-observe
      - home
      - network
      - opengl
      - removable-media